version: '3'
services:
  web:
    build: ./node-server
    ports:
    #  - '127.0.0.1:5000:5000'
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    restart: unless-stopped
  postgres:
    build: ./postgres
    volumes:
      - "/var/lib/postgresql/data"
    # - ./data/:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
     - "5432:5432"
    environment:
     PGDATA: /var/lib/postgresql/data/pgdata
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
    #  PGDATA: /tmp
    #  POSTGRES_DB: auth

  # postgraphql:
  #   build: ./postgraphql
  #   ports:
  #     - '5000:5000'
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

  # postgraphql:
  #   image: postgraphql/postgraphql
  #   ports:
  #       - "5000:5000"
  #   depends_on:
  #     - postgres    
  #   environment:
  #       DB_DEFAULT_ROLE: postgres
  #       DB_GRAPHQL_PATH: "/graphql"
  #       DB_GRAPHIQL_PATH: "/graphiql"
  #       PG_SECRET: "local_secret"
  #       # DB_SCHEMA: "public"
  #       PGUSER: postgres
  #       PGPASSWORD: postgres
  #       PGHOST: postgres
  #       PGDATABASE: auth
  #       # PGDATABASE: postgres
  #       PGPORT: 5432
  #   command: /bin/bash -c "sleep 2 && echo starting && nginx -g 'daemon off;'"     


        # https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945

        #DockerHost asd***